added conditions fpr workflow trigger

diff --git a/.github/workflows/security-checks.yml b/.github/workflows/security-checks.yml
--- a/.github/workflows/security-checks.yml
+++ b/.github/workflows/security-checks.yml
@@ -1,4 +1,4 @@
-name: Security Checks
+name: SecurityChecks
 
 on:
   pull_request:
@@ -28,9 +28,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run semgrep on the repo
-        run: semgrep ci --suppress-errors --sarif --sarif-output=findings.sarif
+        run: |
+          semgrep scan --severity=ERROR --error --config "p/default" --metrics=off --no-autofix --sarif --sarif-output=findings.sarif
+
+      - name: Check if SARIF file exists
+        if: always()
+        run: |
+          if [[ -f "findings.sarif" ]]; then
+            echo "sarif_exists=true" >> $GITHUB_ENV
+          else
+            echo "sarif_exists=false" >> $GITHUB_ENV
+          fi
 
       - name: Upload Artifact
+        if: always() && env.sarif_exists == 'true'  # Check if SARIF exists before uploading
         uses: actions/upload-artifact@v3
         with:
           name: semgrep-scan-results
@@ -41,6 +52,10 @@ jobs:
       #   with:
       #     sarif_file: findings.sarif
       #   if: always()
+
+      # - name: Fail Job if Semgrep Fails
+      #   if: failure()  # Fail the job if semgrep encountered an error
+      #   run: exit 1
 
   Trivy-Scan:
     runs-on: ubuntu-latest
